server:
  port: 8080

spring:
  application:
    name: lhc-zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  sensitiveHeaders:
  routes:
    user_service:
      path: /user/**
      serviceId: lhc-user
    msg_service:
      path: /msg/**
      serviceId: lhc-msg
  host:
    connect-timeout-millis: 3000

logging:
  pattern:
    console: "[%date][%-5level][reqId:%X{requestId}][%logger]-> %msg%n"