server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: lhc-zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-server-ip}:8000/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  sensitiveHeaders:
  routes:
    user_service:
      path: /user/**
      serviceId: lhc-user
    msg_service:
      path: /msg/**
      serviceId: lhc-msg
  host:
    connect-timeout-millis: 3000

logging:
  file:
    clean-history-on-start: true
    max-size: 100MB
    max-history: 7
  pattern:
    console: "[%date][%-5level][reqId:%X{requestId}][%logger]-> %msg%n"
    file: "[LHC-ZUUL][%date][%-5level][reqId:%X{requestId}][%logger]-> %msg%n"

---
spring.profiles: dev
logging.file.name: E:\dev_log\${spring.application.name}.log
eureka-server-ip: 127.0.0.1

---
spring.profiles: pro
logging.file.name: /root/lhc/logs/${spring.application.name}.log
eureka-server-ip: 172.18.0.2