server:
  port: 8080

spring:
  application:
    name: lhc-zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: lhc-zuul-server

zuul:
  sensitiveHeaders:
  routes:
    user_service:
      path: /user/**
      serviceId: lhc-user
    msg_service:
      path: /msg/**
      serviceId: lhc-msg