server:
  port: 8000

spring:
  application:
    name: lhc-eureka-server
  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.instance-id}/eureka

logging:
  file:
    clean-history-on-start: true
    max-size: 100MB
    max-history: 7
  pattern:
    console: "[%date][%-5level][reqId:%X{requestId}][%logger]-> %msg%n"
    file: "[LHC-EUREKA][%date][%-5level][reqId:%X{requestId}][%logger]-> %msg%n"

---
spring.profiles: dev
logging.file.path: E:\dev_log

---
spring.profiles: pro
logging.file.path: /root/lhc/logs

