server:
  port: 8200

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ms_api?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  application:
    name: lhc-msg

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

  instance:
    hostname: localhost
    instance-id: lhc-msg

logging:
#  pattern:
#    console: I[%date][%level]-%msg%n

  level:
    root: info
    org.hibernate: info
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.hjg: info

jwt:
  key: yanzhou__jghuang
  expire: 3h